name: Check new patch
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  run:
    name: Check new patch Revanced
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check new patch ReVanced
        env:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
        run: bash ci.sh "$token" "$repository"